version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.1-debian-10'
    #image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=presta_presta
      - MARIADB_DATABASE=presta_presta
      - MARIADB_PASSWORD=xxxxxxxx
    volumes:
      - 'mariadb_data2:/bitnami/mariadb'
  prestashop:
    build: 
       dockerfile: docker/prestashop/Dockerfile 
       context: .
    ports:
      - '80:80'
      - '443:443'
    environment:
      #- PS_UPDATE_SETTING=1
      - PS_DEMO_MODE=0
      - DB_SERVER=mariadb
      - DB_USER=presta_presta
      - DB_NAME=presta_presta
      - DB_PASSWD=xxxxxxxx
      - PS_INSTALL_AUTO=0
      - PS_LANGUAGE=pl
      - PS_COUNTRY=pl
    volumes:
      - ./eldor24.pl/config/defines.inc.php:/var/www/html/config/defines.inc.php
      - ./eldor24.pl/config/settings.inc.php:/var/www/html/config/settings.inc.php
      - ./eldor24.pl/modules:/var/www/html/modules
      - ./eldor24.pl/override:/var/www/html/override
      - ./eldor24.pl/themes/eldor24:/var/www/html/themes/eldor24
    depends_on:
      - mariadb
volumes:
  mariadb_data2:
    driver: local
